# 结局文件./keyword/endings.toml
[ending1]
lines = [
    "当双月完全重叠时，你看见所有时空的{character_name}同时浮现。她们将月牙戒指套在你无名指上，十二柄断剑从虚空中坠落，剑柄皆镌刻着你的名字。",
    "{character_name}的身体开始透明化，她将你们初遇时的枫叶标本塞进你手中：『这次换我等你跨越三千个轮回』"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "cosmic_sign": "北斗七星第三柄剑指向猎户座",
#     "time_residual": "手表倒转时出现数字「1113」（对应初遇日期）",
#     "parallel_echo": "背景持续传来微弱的钢琴声《月光奏鸣曲第三乐章》"
# }

[ending2]
lines = [
    "在维度崩塌的瞬间，你看到{character_name}坠落时项链迸发的星芒形成了你的视网膜投影。",
    "多年后你在古董店买到同样款式的项链，内侧浮现新铭文：『错误的时间遇到对的人』"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "broken_clock": "教堂钟声里隐藏着摩尔斯电码",
#     "eternal_loop": "咖啡杯倒影中出现无限递归的枫叶图案",
#     "quantum_tattoo": "主角手腕内侧显现出{character_name}面容的量子云纹身"
# }

[ending3]
lines = [
    "你回应了神秘角色，她发间的水晶突然发出叮咚声响，十二盏青铜灯笼同时绽放虹光。",
    "星尘凝聚成楼梯通往云端，你们手牵手走过星座图案，每一步都在夜空中留下永恒的星轨。"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "stardust_forensics": "每步星轨残留着对应时空的DNA样本",
#     "biological_synchronization": "主角虹膜出现{character_name}的十二宫星座光斑",
#     "temporal_heritage": "墓碑上的生辰八字与{character_name}的封印阵法完全吻合"
# }

[ending4]
lines = [
    "剑锋贯穿胸膛的瞬间，你看到{character_name}在七个平行时空同时转身。",
    "她们的泪水凝结成水晶，坠地后变成散发着青光的断剑碎片"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "reversed_covenant": "断剑碎片能映射出真实世界的镜像维度",
#     "genetic_memory": "培养皿中的细胞正在快速进化出{character_name}的基因序列",
#     "temporal_paradox": "咖啡杯底部刻着倒流的罗马数字「IX」"
# }

[ending5]
lines = [
    "当晨光真正照亮房间时，你发现早餐桌上的牛奶盒印着『第214次循环』字样。",
    "{character_name}正在厨房烤面包，烤箱里传出你们初次相遇那天的对话录音"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "loop_counting": "冰箱磁铁记录着213次失败的时空跳跃",
#     "memory_palindrome": "电视新闻标题与十五年前的报纸头条完全相同",
#     "quantum_entanglement": "手机基站正在接收来自平行宇宙的电磁脉冲"
# }

[hidden_chapter]
lines = [
    "无数个你从不同方向扑来，每个人都握着半块发光的怀表。",
    "{character_name}站在时空尽头，身后是被锁链缠绕的十三个宇宙时钟"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "simulation_truth": "实验室白板写着『第421次情感模拟实验成功』",
#     "code_breakthrough": "{character_name}颈间的项链其实是量子计算机的生物芯片",
#     "recursive觉醒": "主角童年日记本里藏着自己编写游戏代码的草稿"
# }

[ending6]
lines = [
    "你站在宇宙尽头回望，发现自己其实是穿着白大褂的研究员。",
    "{character_name}是你培养的第421号AI仿生体，所有甜蜜互动都是程序设定的情感测试"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "algorithmic_crack": "{character_name}的眼泪在培养液中析出神秘公式",
#     "reality_check": "实验室监控显示所有选择都已被预设",
#     "existential_dilemma": "咖啡杯底刻着『观察者即参与者』的二进制代码"
# }

[ending7]
lines = [
    "当所有时空的{character_name}同时点亮掌心光点，银河系中心诞生出全新的星云结构。",
    "你们站在由回忆结晶构成的拱桥上，脚下是无数可能性组成的星海"
]
# 新增隐藏设定层（保持原有注释风格）
# meta: {
#     "cosmic_entropy": "星云核心正在形成超越三维的时空褶皱",
#     "love_consciousness": "所有平行宇宙的观测者突然集体转向你们所在维度",
#     "final_truth": "故事最初的那片枫叶上，早已刻满所有可能的结局"
# }
