# 结局文件
[ending1]
lines = [
    "你选择了离开，神秘角色没有挽留你。",
    "你独自走出了森林。"
]

[ending2]
lines = [
    "你强硬地离开了，神秘角色看起来很失望。",
    "你再也没有见到他。"
]

[ending3]
lines = [
    "你回应了神秘角色，他露出了温暖的笑容。",
    "你们成为了朋友，一起探索森林的秘密。"
]
